# Generated by Django 5.1.6 on 2025-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_listing_latitude_listing_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="shareable",
            field=models.BooleanField(default=False),
        ),
    ]
