# Generated by Django 5.1.6 on 2025-06-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_listing_shareable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_status",
            field=models.CharField(
                choices=[
                    ("O", "Open"),
                    ("P", "Private"),
                    ("F", "Filled"),
                    ("S", "Sent"),
                    ("U", "Under Review"),
                    ("R", "Rejected"),
                    ("I", "Approved - Invited"),
                ],
                default="O",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="RoommateUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("move_in_date", models.DateField()),
                ("stay_length", models.IntegerField(null=True)),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("S", "Student"),
                            ("E", "Employed"),
                            ("N", "Not Currently Working"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "roommate_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("smoke_friendly", models.BooleanField(default=False)),
                ("cannabis_friendly", models.BooleanField(default=False)),
                ("pet_friendly", models.BooleanField(default=False)),
                ("couple_friendly", models.BooleanField(default=False)),
                (
                    "gender_preference",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Open")],
                        max_length=1,
                    ),
                ),
                ("open_to_message", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="listing_groups", to="marketplace.roommateuser"
            ),
        ),
    ]
