# Generated by Django 5.1.6 on 2025-06-11 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_group_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_owner",
                to="marketplace.roommateuser",
            ),
        ),
    ]
