# Generated by Django 5.1.6 on 2025-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_alter_group_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceuser",
            name="yearly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
