# Generated by Django 5.1.6 on 2025-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_groupinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewee_role",
            field=models.CharField(
                choices=[("T", "Tenant"), ("L", "Landlord"), ("R", "Roommate")],
                max_length=1,
            ),
        ),
    ]
