# Generated by Django 5.1.6 on 2025-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_listing_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="condo_fee",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="condo_fee_payable_by_tenant",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="hoa_fee",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="hoa_fee_payable_by_tenant",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="property_taxes",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="property_taxes_payable_by_tenant",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="security_deposit",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="security_deposit_payable_by_tenant",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="utilities_cost",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="utilities_payable_by_tenant",
        ),
        migrations.AddField(
            model_name="listing",
            name="fridge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="heat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="hydro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="internet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="water",
            field=models.BooleanField(default=False),
        ),
    ]
